### ISSUE TITLE
Edges between column objects aren’t displayed in the neo4j graph

### ISSUE THREAD

**Issue by kgaydukova** [oncodash/ontoweaver#12]
When we describe additional connection for column objects, after running ontoweaver we will have this edge in **biocypher-out** and it will be in **neo4j import file**, but it won’t appear in **neo4j graph**. 

For example, you can use edge between **sample** and **patient** in tests:  
For running :` pytest tests/test_edges_between_columns.py `

**Comment by kgaydukova** [comment]
The problem is in csv file for the additional edge for neo4j import (SampleToPatient-part000.csv). 

I’ll explain for our **test example** with the lost **SampleToPatient** edge:

When we create our regular edges (**row -> column**), we now add the name of the column to the nodes (_0:variant -> sample1:sample_, _0:variant -> patient1:patient_).

But when we create additional edges (**column -> column**), we don’t add the name of the column to the nodes and, as a result, we will have our primary data in the final csv file for this additional edge (_sample1 -> patient1_). That is why neo4j won’t recognise this additional connection in the resulted graph.

For simplify understanding of difference:

For now we have this SampleToPatient-part000.csv file in Biocypher-out :

```
sample1;patient1;SampleToPatient
sample2;patient2;SampleToPatient
sample3;patient3;SampleToPatient
sample4;patient4;SampleToPatient

```
But we should have like this :

```
sample1:sample;patient1:patient;SampleToPatient
sample2:sample;patient2:patient;SampleToPatient
sample3:sample;patient3:patient;SampleToPatient
sample4:sample;patient4:patient;SampleToPatient
```

I checked, the edge **SampleToPatient** will successfully appear in our graph with changed csv file.

**Comment by kgaydukova** [comment]
Simple solution : 
    
```
def end(self):
        from . import types
        # Manual extraction of an additional edge between sample and patient.
        # Because so far the PandasAdapter only allow to declare one mapping for each column.
        for i,row in self.df.iterrows():
            #sid = row["sample"]
            #pid = row["patient"]
            sid = row["sample"] + ':sample'
            pid = row['patient'] + ':patient'
            logging.debug(f"Add a `sample_to_patient` edge between `{sid}` and `{pid}`")
            self.edges_append( self.make_edge(
                types.sample_to_patient, id=None,
                id_source=sid, id_target=pid
            ))
```
Good solution for future needs to be discussed

**Comment by mbaric758** [comment]
Hi @kgaydukova , the issue was happening due to a refactoring of the code for edge creation. I updated the readme with new instructions on how to declare edges between columns, so it should work correctly now.

**Comment by kgaydukova** [comment]
Thank you for your help, Marko!
