### ISSUE TITLE
Add a fixed propetry to certain node type

### ISSUE THREAD

**Issue by njmmatthieu** [oncodash/ontoweaver#53]
Hi, 
Would it be possible to have a feature to ontoweaver allowing the user to add a fixed property, just like metadata, but only for certain node types ?
Thanks, 
Matthieu

**Comment by mbaric758** [comment]
Achieved by [73de317](https://github.com/oncodash/ontoweaver/commit/73de3173e0d3f8def1a70fb976339afbdeed1110).
