### ISSUE TITLE
test_simplest.py

### ISSUE THREAD

**Issue by CyrielleGiard** [oncodash/ontoweaver#8]
Hello,

I ran the "pytest" command following the tutorial without any issues.
However, I can't find the written file.
Is the test supposed to return something? If so, where is it?

Thank you

**Comment by jdreo** [comment]
Hi, thanks for the question!

The output file created by BioCypher is put in a timestamped subdirectory in the `biocypher-out` directory.

With the next version of BioCypher, OntoWeaver will be able to print the complete file path, so that this will be clearer.

**Comment by jdreo** [comment]
I added some explanations in the README (see commit [646e007](https://github.com/oncodash/ontoweaver/commit/646e00744a9baa37abd43984aeb23127be7e4bca)).

**Comment by jdreo** [comment]
If you think it is still not clear enough, do not hesitate to suggest or submit an improvement. Else, I will close the issue here after some time, to mark it as done.

**Comment by CyrielleGiard** [comment]
Thank you, it is clear.
